"""EU AI Act Article 53(1)(d) — training-content summary generator.

WHAT THIS IS
------------
Article 53(1)(d) of Regulation (EU) 2024/1689 requires every provider placing a
general-purpose AI model on the Union market to publish a "sufficiently detailed
summary of the content used for training", using the template the AI Office
published on 2025-07-24. Obligations applied from 2025-08-02; the Commission's
enforcement powers and fines activated 2026-08-02. Models placed on the market
before 2025-08-02 must publish by 2027-08-02.

The template asks for three blocks:

  1. model / provider identification        — you supply; a corpus cannot know it
  2. the data sources actually used         — Shuddhi records this per shard
  3. processing and governance              — copyright, illegal content, data
                                              protection: Shuddhi measures this

Shuddhi already carries blocks 2 and 3 as a by-product of admitting a shard at
all: `source`, `license`, `data_class`, `language` and `date_acquired` are
REQUIRED fields — a shard missing any of them is refused, not defaulted. So this
module does not compute anything new. It projects the registry and the build
manifest onto the shape the template asks for.

WHAT THIS IS NOT
----------------
**This does not make anyone compliant, and it must never claim to.** Compliance
is a legal position held by a provider, not a property of a tool. This emits a
DRAFT summary, grounded in what was actually recorded, for your counsel to
review, complete and file. Every field the registry cannot know is printed as an
explicit gap rather than silently omitted or guessed — an incomplete summary you
can see is worth more than a confident one that is wrong.

WHY THE HONESTY MATTERS HERE
----------------------------
A wrong benchmark number embarrasses you. A wrong regulatory filing is a
different category of problem. So: no interpolation, no "probably", and the
report states its own limits in the output itself, where the reader will see
them, rather than in documentation they will not read.
"""

from __future__ import annotations

import json
import time
from collections import Counter, defaultdict

TEMPLATE_PUBLISHED = "2025-07-24"
ENFORCEMENT_LIVE = "2026-08-02"
LEGACY_DEADLINE = "2027-08-02"

# The template's source-category vocabulary, and how Shuddhi's admission classes
# project onto it. Shuddhi's classes are deliberately NARROWER than the
# template's: it has no "user data" class because user data is refused, and it
# does not distinguish crawled-vs-public at admission time — the `source` field
# carries that, and we surface sources verbatim rather than infer.
CLASS_TO_TEMPLATE = {
    "public": "Publicly available datasets",
    "licensed": "Licensed datasets (obtained under a licence agreement)",
    "synthetic-own": "Synthetic data generated by the provider",
}

# Categories the template lists that Shuddhi structurally cannot contribute to.
# Reporting these as an explicit, reasoned "none" is stronger than silence.
STRUCTURAL_NONE = {
    "User data": (
        "None. The engine refuses data_class 'customer' and 'customer-derived' "
        "unconditionally (registry.py::_refusal_reason returns before any other "
        "branch; there is no flag, environment variable or plugin hook that "
        "admits it). A build containing user data cannot be produced."
    ),
}


def _fmt_int(n: int) -> str:
    return f"{n:,}"


# The fields that only a filtered build (`factory.py build`) can produce. A
# corpus manifest from `factory.py run` carries none of them, and the two are
# easy to confuse because both are called a manifest and both sit in runs/.
FILTERED_BUILD_KEYS = ("filtered_build_hash", "kept_docs")


def _is_filtered_build(manifest: dict) -> bool:
    """True only for a manifest that actually describes a filter pass."""
    return any(k in manifest for k in FILTERED_BUILD_KEYS)


def build_summary(meta: dict, accepted: list, refused: list,
                  manifest: dict | None = None) -> str:
    """Render the draft Article 53 summary as Markdown.

    meta/accepted/refused come from registry_mod.load_registry().
    manifest is an optional BUILD-MANIFEST.json dict — when present the
    processing block is grounded in what a build actually did, not merely what
    the pipeline is capable of.
    """
    L: list[str] = []
    gaps: list[str] = []

    def head(t, lvl=2):
        L.append("")
        L.append("#" * lvl + " " + t)
        L.append("")

    L.append("# Public summary of training content")
    L.append("")
    L.append(f"*Draft generated by Shuddhi on "
             f"{time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}.*")
    L.append("")
    L.append("Prepared against the template published by the European Commission's "
             f"AI Office on {TEMPLATE_PUBLISHED} for Article 53(1)(d) of "
             "Regulation (EU) 2024/1689.")
    L.append("")
    L.append("> **This is a draft for legal review, not a compliance statement.** "
             "It reports what the corpus registry and build manifest actually "
             "recorded. Sections marked **GAP** could not be derived from the "
             "corpus and must be completed by the provider before filing.")

    # ---------------------------------------------------------------- block 1
    head("1. Model and provider identification")
    L.append("**GAP — supplied by the provider.** A corpus cannot know which model "
             "was trained on it. Complete: provider legal name and contact, model "
             "name and version, modalities, and the date the model was or will be "
             "placed on the Union market.")
    gaps.append("Block 1: model and provider identification")

    # ---------------------------------------------------------------- block 2
    head("2. Data sources used for training")

    by_class: dict[str, list] = defaultdict(list)
    for s in accepted:
        by_class[s.data_class].append(s)

    L.append(f"Corpus identifier: `{meta.get('corpus_id', '(unset)')}`  ")
    L.append(f"Registry integrity: `sha256:{str(meta.get('registry_sha256', ''))[:32]}…`  ")
    L.append(f"Shards admitted: **{len(accepted)}** · refused: **{len(refused)}**")
    L.append("")

    for cls, label in CLASS_TO_TEMPLATE.items():
        shards = by_class.get(cls, [])
        L.append(f"### {label}")
        L.append("")
        if not shards:
            L.append("None recorded in this corpus.")
            L.append("")
            continue
        L.append(f"{len(shards)} shard(s).")
        L.append("")
        L.append("| Shard | Source | Licence | Language | Acquired |")
        L.append("|---|---|---|---|---|")
        for s in sorted(shards, key=lambda x: x.shard_id):
            L.append(f"| `{s.shard_id}` | {s.source} | {s.license} | "
                     f"{s.language} | {s.date_acquired} |")
        L.append("")

    for label, reason in STRUCTURAL_NONE.items():
        L.append(f"### {label}")
        L.append("")
        L.append(reason)
        L.append("")

    L.append("### Scraped or crawled online content")
    L.append("")
    L.append("Shuddhi does not classify acquisition method at admission; the "
             "`Source` column above states the origin of each shard verbatim as "
             "recorded. **GAP —** if any listed source was obtained by crawling, "
             "the provider must state the crawler identity and the period of "
             "collection, which the corpus does not record.")
    gaps.append("Block 2: crawler identity and collection period, if any source was crawled")
    L.append("")

    # ---------------------------------------------------------------- block 3
    head("3. Processing and governance")

    L.append("### Copyright and text-and-data-mining reservations")
    L.append("")
    licences = Counter(s.license for s in accepted)
    if licences:
        L.append("Licences recorded across admitted shards:")
        L.append("")
        for lic, n in sorted(licences.items(), key=lambda kv: (-kv[1], kv[0])):
            L.append(f"- `{lic}` — {n} shard(s)")
        L.append("")
    L.append("A licence is a **required** registry field: a shard without one is "
             "refused, not admitted with a blank. The licences above are therefore "
             "asserted for every admitted shard, not merely for those that "
             "happened to carry one.")
    L.append("")
    L.append("**GAP —** whether each source honoured a machine-readable TDM "
             "reservation under Article 4(3) of Directive (EU) 2019/790 is a "
             "property of how the data was obtained, which the corpus does not "
             "record. The provider must state its opt-out policy.")
    gaps.append("Block 3: TDM opt-out policy under Directive (EU) 2019/790 Art. 4(3)")
    L.append("")

    L.append("### Personal data")
    L.append("")
    if manifest and "pii_redactions" in manifest:
        L.append(f"Personal-data redactions applied in the reported build: "
                 f"**{_fmt_int(manifest['pii_redactions'])}**.")
    else:
        L.append("*(Run with `--manifest` to report the redaction count from an "
                 "actual build rather than describing capability.)*")
    L.append("")
    L.append("Detectors applied per document: email addresses, Indian mobile "
             "numbers, Aadhaar (12-digit 4-4-4 grouping), PAN, payment-card "
             "numbers validated by the Luhn check, and IPv4 addresses. Matches "
             "are replaced by typed placeholders such as `[PII:email]`. Detection "
             "is pattern-based and conservative by design; it is not a named-entity "
             "model and does not claim exhaustive recall.")
    L.append("")

    L.append("### Measures to detect and remove illegal content")
    L.append("")
    L.append("A lexicon-tier toxicity screen runs per document, matching "
             "per-language term lists on word boundaries and flagging a document "
             "on distinct-term count and hit density. External lexicons mounted "
             "via `--toxicity-lexicon-dir` are SHA-pinned into the build "
             "configuration, so a build states exactly which lists screened it. "
             "This tier catches overtly abusive and adult material; it is not a "
             "classifier and does not reason about context.")
    if manifest and manifest.get("dropped_by_reason"):
        drops = {k: v for k, v in manifest["dropped_by_reason"].items() if v}
        if drops:
            L.append("")
            L.append("Documents removed in the reported build, by reason:")
            L.append("")
            for reason, n in sorted(drops.items(), key=lambda kv: -kv[1]):
                L.append(f"- `{reason}` — {_fmt_int(n)}")
    L.append("")

    L.append("### Provenance and verifiability")
    L.append("")
    if manifest and _is_filtered_build(manifest):
        L.append(f"- Corpus build hash: `{manifest.get('parent_corpus_build_hash', '')}`")
        L.append(f"- Filtered build hash: `{manifest.get('filtered_build_hash', '')}`")
        L.append(f"- Filter configuration: `sha256:{manifest.get('filter_config_sha256', '')}`")
        L.append(f"- Documents retained: **{_fmt_int(manifest.get('kept_docs', 0))}**")
        L.append("")
        L.append("The filtered build hash is chained from the parent corpus hash "
                 "and the filter-configuration hash, so the summary above is bound "
                 "to a specific, reproducible artefact. Re-running the same "
                 "configuration over the same corpus reproduces the same hash.")
    elif manifest:
        # A corpus manifest (from `run`), not a filtered build manifest (from
        # `build`). It identifies the accepted corpus but records nothing about
        # what a filter pass kept or dropped. Reporting those absent fields as
        # 0 or "" would state a measured zero that was never measured — the
        # exact failure this module exists to prevent — so name the artefact
        # we got and ask for the other one.
        cbh = manifest.get("corpus_build_hash", "")
        if cbh:
            L.append(f"- Corpus build hash: `{cbh}`")
            L.append("")
        L.append("**GAP — a corpus manifest was supplied, not a filtered build "
                 "manifest.** It identifies the accepted corpus but records no "
                 "filter pass, so documents retained, redaction counts and the "
                 "filtered build hash are unknown here and are deliberately not "
                 "reported as zero. Pass the `BUILD-MANIFEST.json` written by "
                 "`factory.py build` to bind this summary to a filtered build.")
        gaps.append("Block 3: filtered build manifest (documents retained, "
                    "redactions, filtered build hash)")
    else:
        L.append("*(No build manifest supplied — pass `--manifest "
                 "BUILD-MANIFEST.json` to bind this summary to a specific, "
                 "reproducible build.)*")
    L.append("")

    if refused:
        L.append("### Data excluded at admission")
        L.append("")
        L.append(f"{len(refused)} shard(s) were refused and did not enter training:")
        L.append("")
        for r in refused[:50]:
            L.append(f"- `{r.shard_id}` — {r.reason}")
        if len(refused) > 50:
            L.append(f"- …and {len(refused) - 50} more")
        L.append("")

    # ---------------------------------------------------------------- gaps
    head("Gaps requiring provider input before filing")
    for g in gaps:
        L.append(f"- {g}")
    L.append("")
    L.append(f"Enforcement powers under the Act became active {ENFORCEMENT_LIVE}. "
             f"Models placed on the Union market before 2025-08-02 must publish "
             f"this summary by {LEGACY_DEADLINE}.")
    L.append("")
    L.append("---")
    L.append("")
    L.append("*Generated by Shuddhi from a corpus registry and build manifest. "
             "Shuddhi reports what was recorded; it does not assess legal "
             "sufficiency, and publishing this draft unreviewed is not advisable.*")

    return "\n".join(L) + "\n"


def load_manifest(path: str | None) -> dict | None:
    if not path:
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)
