"""EU AI Act Article 53(1)(d) summary generation.

A wrong benchmark number is embarrassing. A wrong regulatory filing is a
different category of problem, so these tests are weighted towards what the
report must NEVER do — claim compliance, invent a fact, or quietly omit a
field it could not derive — rather than towards formatting.
"""

from pathlib import Path

import eu_ai_act
import registry as registry_mod

# Resolve repo files from this file's location, never from the working
# directory. The container runs `pytest /app/tests` with WORKDIR=/work (the
# mount point for user data), so a relative "examples/registry.json" resolves
# against /work and does not exist -- green everywhere else, red in the image.
EXAMPLE_REGISTRY = Path(__file__).resolve().parent.parent / "examples" / "registry.json"


class FakeShard:
    def __init__(self, sid, source, lic, data_class, language, acquired):
        self.shard_id = sid
        self.source = source
        self.license = lic
        self.data_class = data_class
        self.language = language
        self.date_acquired = acquired
        self.reviewed_by = ""


class FakeRefusal:
    def __init__(self, sid, reason):
        self.shard_id = sid
        self.reason = reason


META = {"corpus_id": "test-corpus", "registry_sha256": "a" * 64}

SHARDS = [
    FakeShard("s_pub", "Wikipedia dump", "CC-BY-SA-4.0", "public", "eng", "2026-01-01"),
    FakeShard("s_lic", "Vendor X agreement", "commercial", "licensed", "hin", "2026-02-01"),
    FakeShard("s_syn", "generated in-house", "CC0-1.0", "synthetic-own", "eng", "2026-03-01"),
]

REFUSALS = [FakeRefusal("s_cust", "data_class 'customer' is never trainable")]


def _summary(shards=SHARDS, refusals=REFUSALS, manifest=None):
    return eu_ai_act.build_summary(META, shards, refusals, manifest)


# ------------------------------------------------------------------ safety --

def test_never_claims_compliance():
    """The single most important assertion in this file.

    Compliance is a legal position held by a provider, not a property of a
    tool. Emitting a document that says otherwise would be worse than emitting
    nothing at all.
    """
    out = _summary().lower()
    for forbidden in ("is compliant", "ensures compliance", "guarantees compliance",
                      "certifies", "legally compliant", "makes you compliant"):
        assert forbidden not in out, f"report claims compliance: {forbidden!r}"


def test_states_it_is_a_draft_for_review():
    out = _summary()
    assert "draft" in out.lower()
    assert "legal review" in out.lower() or "for your counsel" in out.lower()


def test_gaps_are_named_not_silently_omitted():
    """A field the corpus cannot know must appear as an explicit GAP.

    Silence would read as "nothing to declare", which is the dangerous
    failure mode for a regulatory document.
    """
    out = _summary()
    assert "GAP" in out
    assert "Gaps requiring provider input" in out
    # the three the corpus genuinely cannot derive
    assert "provider identification" in out
    assert "crawler" in out.lower()
    assert "opt-out" in out.lower() or "4(3)" in out


# ------------------------------------------------- template block coverage --

def test_every_admission_class_maps_to_a_template_category():
    out = _summary()
    assert "Publicly available datasets" in out
    assert "Licensed datasets" in out
    assert "Synthetic data generated by the provider" in out


def test_shards_appear_with_source_licence_and_language():
    out = _summary()
    for s in SHARDS:
        assert s.shard_id in out
        assert s.source in out
        assert s.license in out


def test_user_data_reported_as_structurally_impossible():
    """The strongest answer available for this template field, and it is true.

    Every other provider must DESCRIBE how they handled user data. Shuddhi's
    honest answer is that a build containing it cannot be produced.
    """
    out = _summary()
    assert "User data" in out
    assert "None." in out
    assert "refuses" in out
    assert "no flag, environment variable or plugin hook" in out


def test_refused_shards_are_disclosed_with_reasons():
    out = _summary()
    assert "s_cust" in out
    assert "never trainable" in out


# ----------------------------------------------------------- manifest bind --

def test_without_manifest_says_so_rather_than_reporting_zero():
    """Absent data must read as absent, never as a measured zero."""
    out = _summary(manifest=None)
    assert "No build manifest supplied" in out
    assert "0 redactions" not in out
    assert "Documents retained: **0**" not in out


def test_with_manifest_binds_the_summary_to_reproducible_hashes():
    manifest = {
        "parent_corpus_build_hash": "b" * 64,
        "filtered_build_hash": "c" * 64,
        "filter_config_sha256": "d" * 64,
        "kept_docs": 12345,
        "pii_redactions": 678,
        "dropped_by_reason": {"toxicity": 9, "dedup": 40, "unused": 0},
    }
    out = _summary(manifest=manifest)
    assert "c" * 64 in out, "filtered build hash must appear"
    assert "12,345" in out, "kept docs must be reported"
    assert "678" in out, "redaction count must be reported"
    assert "`dedup` — 40" in out
    assert "`unused`" not in out, "zero-count drop reasons should not be listed"


def test_empty_corpus_does_not_crash():
    out = eu_ai_act.build_summary(META, [], [], None)
    assert "Shards admitted: **0**" in out
    assert "GAP" in out


# ------------------------------------------------------------- end to end --

def test_runs_against_the_shipped_example_registry():
    """The example corpus deliberately contains a refused customer shard, so
    the demo output shows the refusal inside the compliance artefact."""
    meta, accepted, refused = registry_mod.load_registry(str(EXAMPLE_REGISTRY))
    out = eu_ai_act.build_summary(meta, accepted, refused, None)
    assert len(refused) >= 1
    assert "Data excluded at admission" in out
    assert "customer" in out.lower()


# ------------------------------------------------- wrong-manifest handling --

def test_corpus_manifest_is_not_reported_as_a_measured_zero():
    """The two manifests are easy to confuse — both are called a manifest and
    both live in runs/. A corpus manifest (from `run`) records no filter pass,
    so reporting "Documents retained: 0" from one would put a number in a
    regulatory filing that nothing ever measured."""
    corpus_manifest = {
        "manifest_version": 1,
        "corpus_id": "tatva-sangraha-v1",
        "corpus_build_hash": "e" * 64,
        "shards": [],
    }
    out = _summary(manifest=corpus_manifest)
    assert "Documents retained: **0**" not in out
    assert "0 redactions" not in out
    assert "corpus manifest was supplied" in out
    assert "GAP" in out
    # the hash it DOES legitimately carry should still be reported
    assert "e" * 64 in out


def test_filtered_build_manifest_still_reports_its_numbers():
    """The guard must not suppress a genuine filtered build."""
    out = _summary(manifest={
        "parent_corpus_build_hash": "b" * 64,
        "filtered_build_hash": "c" * 64,
        "filter_config_sha256": "d" * 64,
        "kept_docs": 999,
        "pii_redactions": 7,
    })
    assert "c" * 64 in out
    assert "999" in out
    assert "corpus manifest was supplied" not in out
